// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFRZ9DbKjqb-CPKvnyzQvuosB44yBuFq4',
    appId: '1:1017449721651:web:45ed7d0df7a696aa721846',
    messagingSenderId: '1017449721651',
    projectId: 'campus-marketplace-2026-351',
    authDomain: 'campus-marketplace-2026-351.firebaseapp.com',
    storageBucket: 'campus-marketplace-2026-351.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWHGmsWicZBektwy29O4mqIGik8huKNfs',
    appId: '1:1017449721651:android:05a6cc6195b0221e721846',
    messagingSenderId: '1017449721651',
    projectId: 'campus-marketplace-2026-351',
    storageBucket: 'campus-marketplace-2026-351.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmA6ztLhGlOc4KqmwawsBixl9BXzCWtOk',
    appId: '1:1017449721651:ios:a1da5e032a9a4872721846',
    messagingSenderId: '1017449721651',
    projectId: 'campus-marketplace-2026-351',
    storageBucket: 'campus-marketplace-2026-351.firebasestorage.app',
    iosBundleId: 'com.example.campusMarketplaceW7',
  );
}
